name: Fetch Pokemon Card Lottery Tweets

on:
  schedule:
    # 毎日9:00 JST (0:00 UTC) - Twitter API制限のため1日1回に変更
    - cron: '0 0 * * *'
  workflow_dispatch:  # 手動実行も可能

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Fetch tweets
      env:
        TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
      run: |
        python fetch_tweets.py

    - name: Send email notification
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        python send_email.py

    - name: Upload results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: lottery-tweets-${{ github.run_id }}
        path: |
          *_tweets.json
        retention-days: 30
